package motorinwheel.common.ports.matter;

import java.util.Optional;
import motorinwheel.common.events.AirResistanceEvent;
import motorinwheel.common.signals.AirResistanceSignal;
import sysmlinjava.blocks.SysMLBlock;
import sysmlinjava.common.SysMLSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.ports.SysMLFullPort;

/**
 * Port to receive the force of air resistance on the vehicle
 * 
 * @author ModelerOne
 *
 */
public class AirResistanceReceivePort extends SysMLFullPort
{
	/**
	 * Constructor
	 * 
	 * @param contextBlock      block in whose context the port resides
	 * @param eventContextBlock block to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public AirResistanceReceivePort(SysMLBlock contextBlock, SysMLBlock eventContextBlock, Long id)
	{
		super(contextBlock, Optional.of(eventContextBlock), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if(signal instanceof AirResistanceSignal)
			result = new AirResistanceEvent(((AirResistanceSignal)signal).force, id);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}
}
