package trafficcontrolsystem;

import static sysmlinjava.verifications.SysMLVerdictKind.pass;

import java.util.List;
import java.util.Optional;

import sysmlinjava.events.SysMLChangeEvent;
import sysmlinjava.javaannotations.actions.VerificationCaseAction;
import sysmlinjava.verifications.SysMLVerdictKind;
import sysmlinjava.verifications.SysMLVerificationCase;

/**
 * Test/verification case of the {@code TrafficControlSystem} model. The test
 * case simply injects events into the system model for an emergency vehicle
 * approaching and departing the system from different directions and at
 * different times. The verdict defaults to "pass", but the verification is
 * presumed to be performed by visual inspection of the state timing diagrams
 * that are generated by the intersection state machines.
 * 
 * @author ModelerOne
 *
 */
public class TrafficSignalControlSystemVerificationCase extends SysMLVerificationCase
{
	/**
	 * The Traffic Control System (system-under-test) that will be tested.
	 */
	TrafficSignalControlSystem tcs;

	static final String changeExpressionFormat = "directionDegrees=%s";

	static final String none = "none";

	/**
	 * Constructor
	 * 
	 */
	public TrafficSignalControlSystemVerificationCase()
	{
		super("TrafficSignalControlSystemTest", 0L, Optional.empty());
	}

	@VerificationCaseAction
	@Override
	public void perform()
	{
		SysMLVerdictKind verdict = initializeTest();
		if (verdict == pass)
			verdict = executeTest();
		finalizeTest();
	}

	@VerificationCaseAction
	private SysMLVerdictKind initializeTest()
	{
		verdict = SysMLVerdictKind.fail;
		tcs = new TrafficSignalControlSystem();
		tcs.start();
		return SysMLVerdictKind.pass;
	}

	@VerificationCaseAction
	private SysMLVerdictKind executeTest()
	{
		logger.info("start");
		logger.info("delay 120sec");
		delay(120);
		logger.info("tcs.acceptEvent(EV approach west)");
		tcs.acceptEvent(new SysMLChangeEvent(String.format(changeExpressionFormat, "west"), "EmergencyVehicleApproachWestEvent", 0L));
		logger.info("delay 60sec");
		delay(60);
		logger.info("tcs.acceptEvent(EV departs)");
		tcs.acceptEvent(new SysMLChangeEvent(String.format(changeExpressionFormat, none), "EmergencyVehicleDepartsEvent", 0L));
		logger.info("delay 90sec");
		delay(90);
		logger.info("tcs.acceptEvent(EV approach east)");
		tcs.acceptEvent(new SysMLChangeEvent(String.format(changeExpressionFormat, "east"), "EmergencyVehicleApproachEastEvent", 0L));
		logger.info("delay 60sec");
		delay(60);
		logger.info("tcs.acceptEvent(EV departs)");
		tcs.acceptEvent(new SysMLChangeEvent(String.format(changeExpressionFormat, none), "EmergencyVehicleDepartsEvent", 0L));
		logger.info("delay 75sec");
		delay(75);
		logger.info("tcs.acceptEvent(EV approach west)");
		tcs.acceptEvent(new SysMLChangeEvent(String.format(changeExpressionFormat, "west"), "EmergencyVehicleApproachWestEvent", 0L));
		logger.info("delay 45sec");
		delay(45);
		logger.info("tcs.acceptEvent(EV departs");
		tcs.acceptEvent(new SysMLChangeEvent(String.format(changeExpressionFormat, none), "EmergencyVehicleDepartsEvent", 0L));
		logger.info("delay 120sec");
		delay(120);
		logger.info("done!");
		return SysMLVerdictKind.pass;
	}

	@VerificationCaseAction
	private SysMLVerdictKind finalizeTest()
	{
		tcs.stop();
		return SysMLVerdictKind.pass;
	}

	@Override
	protected void createObjective()
	{
		objective = TrafficSignalControlSystemRequirements.testObjective;
	}

	@Override
	protected void createSubject()
	{
		subject = Optional.of(TrafficSignalControlSystem.class);
	}

	@Override
	protected void createActors()
	{
		actors = List.of();
	}

	/**
	 * Main method to create and perform verification
	 * 
	 * @param args args not used
	 */
	public static void main(String[] args)
	{
		TrafficSignalControlSystemVerificationCase test = new TrafficSignalControlSystemVerificationCase();
		test.perform();
	}
}
