package trafficcontrolsystem;

import java.util.Optional;
import sysmlinjava.tests.SysMLTestCase;
import sysmlinjava.tests.SysMLVerdictKind;
import sysmlinjava.valuetypes.DirectionDegrees;

/**
 * Test case of the {@code TrafficControlSystem} model. The test case simply
 * injects events into the system for an emergency vehicle approaching and
 * departing the system from different directions and at different times. The
 * verdict defaults to "pass", but the verification is presumed to be performed
 * by visual inspection of the state timing diagrams that are generated by the
 * intersection state machines.
 * 
 * @author ModelerOne
 *
 */
public class TrafficControlSystemTestCase extends SysMLTestCase
{
	/**
	 * Constructor
	 * 
	 * @param test test of which this test case is a part of
	 */
	public TrafficControlSystemTestCase(TrafficControlSystemTest test)
	{
		super(test);
	}

	@Override
	protected void createInitializeActivity()
	{
		initialize = Optional.of(() -> ((TrafficControlSystemTest)test).tcs.start());
	}

	@Override
	protected void createExecuteActivity()
	{
		execute = () ->
		{
			verdict = SysMLVerdictKind.fail;
			delay(120);
			((TrafficControlSystemTest)test).tcs.acceptEvent(new EmergencyVehicleChangeEvent(Optional.of(DirectionDegrees.west)));
			delay(60);
			((TrafficControlSystemTest)test).tcs.acceptEvent(new EmergencyVehicleChangeEvent(Optional.empty()));
			delay(90);
			((TrafficControlSystemTest)test).tcs.acceptEvent(new EmergencyVehicleChangeEvent(Optional.of(DirectionDegrees.east)));
			delay(60);
			((TrafficControlSystemTest)test).tcs.acceptEvent(new EmergencyVehicleChangeEvent(Optional.empty()));
			delay(75);
			((TrafficControlSystemTest)test).tcs.acceptEvent(new EmergencyVehicleChangeEvent(Optional.of(DirectionDegrees.west)));
			delay(45);
			((TrafficControlSystemTest)test).tcs.acceptEvent(new EmergencyVehicleChangeEvent(Optional.empty()));
			delay(120);
			verdict = SysMLVerdictKind.pass;
		};
	}

	@Override
	protected void createFinalizeActivity()
	{
		finalize = Optional.of(() -> ((TrafficControlSystemTest)test).tcs.stop());
	}
}
