package hflink.common.ports;

import java.util.Optional;

import hflink.common.items.ApplicationUIControl;
import hflink.common.items.ApplicationUIControlString;
import hflink.common.items.ApplicationUIView;
import hflink.common.signals.ApplicationUIViewSignal;
import sysmlinjava.annotations.SysMLHyperlink;
import sysmlinjava.common.SysMLAnything;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.javaannotations.annotations.Hyperlink;
import sysmlinjava.javaannotations.requirements.RequirementSpecificationLink;
import sysmlinjava.ports.SysMLPort;
import sysmlinjava.states.StateBehaviorContext;

/**
 * Port that simulates the protocol for input and output of application
 * information from and to the operator
 * 
 * @author ModelerOne
 *
 */
public class ApplicationUIClientProtocol extends SysMLPort
{
	/**
	 * Standard spec for the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor
	 * 
	 * @param context      block in whose context the port resides
	 * @param eventContext block to receive signal events generated by the port
	 * @param id                unique ID
	 */
	public ApplicationUIClientProtocol(StateBehaviorContext context, StateBehaviorContext eventContext, Long id)
	{
		super(context, Optional.of(eventContext), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLAnything object)
	{
		SysMLSignalEvent result = null;
		if (object instanceof ApplicationUIView)
			result = new SysMLSignalEvent(new ApplicationUIViewSignal((ApplicationUIView)object), "", 0L);
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLAnything serverObjectFor(SysMLAnything clientObject)
	{
		SysMLAnything result = null;
		if (clientObject instanceof ApplicationUIControlString)
			result = new ApplicationUIControl((ApplicationUIControlString)clientObject);
		else
			logger.warning("unexpected client object type: " + clientObject.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createSupportingInformationLinks()
	{
		protocolStandard = new SysMLHyperlink("AppUI Client Protocol", "file://IRS for Application UI Client Protocol");
	}
}