package hflink.common.ports;

import java.util.Optional;

import hflink.common.items.ApplicationUIControl;
import hflink.common.items.ApplicationUIView;
import hflink.common.items.ApplicationUIViewString;
import hflink.common.signals.ApplicationUIControlSignal;
import sysmlinjava.common.SysMLAnything;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.ports.SysMLPort;
import sysmlinjava.states.StateBehaviorContext;

/**
 * Port that simulates the protocol for input and output by the operator of
 * information from and to the application
 * 
 * @author ModelerOne
 *
 */
public class ApplicationUIServerProtocol extends SysMLPort
{
	/**
	 * Constructor
	 * 
	 * @param context      block in whose context the port resides
	 * @param eventContext block to receive signal events generated by the port
	 * @param id           unique ID
	 */
	public ApplicationUIServerProtocol(StateBehaviorContext context, StateBehaviorContext eventContext, Long id)
	{
		super(context, Optional.of(eventContext), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLAnything object)
	{
		SysMLSignalEvent result = null;
		if (object instanceof ApplicationUIControl)
			result = new SysMLSignalEvent(new ApplicationUIControlSignal((ApplicationUIControl)object), "ApplicationUIControlEvent", 0L);
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLAnything serverObjectFor(SysMLAnything clientObject)
	{
		SysMLAnything result = null;
		if (clientObject instanceof ApplicationUIViewString)
			result = new ApplicationUIView((ApplicationUIViewString)clientObject);
		else
			logger.warning("unexpected client object type: " + clientObject.getClass().getSimpleName());
		return result;
	}
}