package hflink.common.ports;

import java.util.Optional;

import hflink.common.items.DataLinkFrame;
import hflink.common.signals.DataLinkFrameSignal;
import sysmlinjava.annotations.SysMLHyperlink;
import sysmlinjava.common.SysMLAnything;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.javaannotations.annotations.Hyperlink;
import sysmlinjava.javaannotations.requirements.RequirementSpecificationLink;
import sysmlinjava.ports.SysMLPort;
import sysmlinjava.states.StateBehaviorContext;

/**
 * Port that simulates the protocol to receive data-link frames
 * 
 * @author ModelerOne
 *
 */
public class DataLinkReceiveProtocol extends SysMLPort
{
	/**
	 * Standard specification for the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor
	 * 
	 * @param context      block in whose context the port resides
	 * @param eventContext block to receive signal events generated by the port
	 * @param id                unique ID
	 */
	public DataLinkReceiveProtocol(StateBehaviorContext context, StateBehaviorContext eventContext, Long id)
	{
		super(context, Optional.of(eventContext), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLAnything object)
	{
		SysMLSignalEvent result = null;
		if (object instanceof DataLinkFrame)
			result = new SysMLSignalEvent(new DataLinkFrameSignal((DataLinkFrame)object), "DataLinkFrameEvent", 0L);
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createSupportingInformationLinks()
	{
		protocolStandard = new SysMLHyperlink("IRS for Data Link Receive Protocol", "file://IRS for Data Link Receive Protocol");
	}

}
