package hflink.common.ports;

import java.util.Optional;

import hflink.common.items.EthernetPacket;
import hflink.common.items.IPPacket;
import hflink.common.signals.EthernetPacketSignal;
import sysmlinjava.annotations.SysMLHyperlink;
import sysmlinjava.common.SysMLAnything;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.items.SysMLSignal;
import sysmlinjava.javaannotations.actions.Action;
import sysmlinjava.javaannotations.annotations.Hyperlink;
import sysmlinjava.javaannotations.requirements.RequirementSpecificationLink;
import sysmlinjava.ports.SysMLPort;
import sysmlinjava.states.StateBehaviorContext;

/**
 * Port to simulate the ethernet protocol
 * 
 * @author ModelerOne
 *
 */
public class EthernetProtocol extends SysMLPort
{
	/**
	 * Standard that specifies the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor for protocol that operates synchronously with user (transmit() caller)
	 * 
	 * @param context      context (part, port) in which the port resides
	 * @param eventContext context (part, port) to receive signal events generated by the port
	 * @param id                unique ID
	 */
	public EthernetProtocol(StateBehaviorContext context, StateBehaviorContext eventContext, Long id)
	{
		super(context, Optional.of(eventContext), id);
	}

	/**
	 * Constructor for protocol that operates asynchronously from user (transmit() caller)
	 * 
	 * @param context block in whose context the port resides
	 * @param id           unique ID
	 */
	public EthernetProtocol(StateBehaviorContext context, Long id)
	{
		super(context, id);
		this.eventContext = Optional.of(this);
	}

	/**
	 * Reception that reacts to the receipt of an ethernet packet by the port
	 * 
	 * @param packet ethernet packet received by the protocol
	 */
	@Action
	public void onEthernetPacketReceived(EthernetPacket packet)
	{
		receive(packet);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if (signal instanceof EthernetPacketSignal)
		{
			EthernetPacketSignal ethernetPacketSignal = (EthernetPacketSignal)signal;
			EthernetPacket ethernetPacket = ethernetPacketSignal.packet;
			result = new SysMLSignalEvent(new EthernetPacketSignal(ethernetPacket), "EthernetPacketEvent", 0L);
		}
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLAnything clientObjectFor(SysMLAnything object)
	{
		SysMLAnything result = null;
		if (object instanceof EthernetPacket)
		{
			EthernetPacket ethernetPacket = (EthernetPacket)object;
			result = ethernetPacket.frame;
		}
		else
			logger.warning("unexpected signal type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLSignal signalFor(SysMLAnything object)
	{
		SysMLSignal result = null;
		if (object instanceof IPPacket)
		{
			IPPacket ipPacket = (IPPacket)object;
			EthernetPacket packet = new EthernetPacket(this.id, connectedPortsPeers.get(0).id, ipPacket);
			result = new EthernetPacketSignal(packet);
		}
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createStateMachine()
	{
		stateMachine = Optional.of(new EthernetProtocolStateMachine(this));
	}

	@Override
	protected void createSupportingInformationLinks()
	{
		protocolStandard = new SysMLHyperlink("IEEE 802.3 Ethernet", "https://standards.ieee.org/standard/802_3-2018.html");
	}
}
