package hflink.common.ports;

import java.util.Optional;
import hflink.common.events.EthernetPacketEvent;
import hflink.common.objects.EthernetPacket;
import hflink.common.objects.IPPacket;
import hflink.common.signals.EthernetPacketSignal;
import sysmlinjava.annotations.Reception;
import sysmlinjava.annotations.comments.Hyperlink;
import sysmlinjava.annotations.requirements.RequirementSpecificationLink;
import sysmlinjava.blocks.SysMLBlock;
import sysmlinjava.comments.SysMLHyperlink;
import sysmlinjava.common.SysMLClass;
import sysmlinjava.common.SysMLSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.ports.SysMLFullPort;

/**
 * Port to simulate the ethernet protocol
 * 
 * @author ModelerOne
 *
 */
public class EthernetProtocol extends SysMLFullPort
{
	/**
	 * Standard that specifies the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor for protocol that operates synchronously with user (transmit() caller)
	 * 
	 * @param contextBlock      block in whose context the port resides
	 * @param eventContextBlock block to receive signal events generated by the port
	 * @param id                unique ID
	 */
	public EthernetProtocol(SysMLBlock contextBlock, SysMLBlock eventContextBlock, Long id)
	{
		super(contextBlock, Optional.of(eventContextBlock), id);
	}

	/**
	 * Constructor for protocol that operates asynchronously from user (transmit() caller)
	 * 
	 * @param contextBlock block in whose context the port resides
	 * @param id           unique ID
	 */
	public EthernetProtocol(SysMLBlock contextBlock, Long id)
	{
		super(contextBlock, id);
		this.eventContextBlock = Optional.of(this);
	}

	/**
	 * Reception that reacts to the receipt of an ethernet packet by the port
	 * 
	 * @param packet ethernet packet received by the protocol
	 */
	@Reception
	public void onEthernetPacketReceived(EthernetPacket packet)
	{
		receive(packet);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if (signal instanceof EthernetPacketSignal)
		{
			EthernetPacketSignal ethernetPacketSignal = (EthernetPacketSignal)signal;
			EthernetPacket ethernetPacket = (EthernetPacket)ethernetPacketSignal.packet;
			result = new EthernetPacketEvent(ethernetPacket);
		}
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLClass clientObjectFor(SysMLClass object)
	{
		SysMLClass result = null;
		if (object instanceof EthernetPacket)
		{
			EthernetPacket ethernetPacket = (EthernetPacket)object;
			result = (SysMLClass)ethernetPacket.frame;
		}
		else
			logger.warning("unexpected signal type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLSignal signalFor(SysMLClass object)
	{
		SysMLSignal result = null;
		if (object instanceof IPPacket)
		{
			IPPacket ipPacket = (IPPacket)object;
			EthernetPacket packet = new EthernetPacket(this.id, connectedPortsPeers.get(0).id, ipPacket);
			result = new EthernetPacketSignal(packet);
		}
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createStateMachine()
	{
		this.stateMachine = Optional.of(new EthernetProtocolStateMachine(this));
	}

	@Override
	protected void createHyperlinks()
	{
		protocolStandard = new SysMLHyperlink("IEEE 802.3 Ethernet", "https://standards.ieee.org/standard/802_3-2018.html");
	}
}
