package hflink.common.ports;

import java.util.Optional;

import hflink.common.signals.GPSMessageSignal;
import sysmlinjava.annotations.SysMLHyperlink;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.items.SysMLSignal;
import sysmlinjava.javaannotations.annotations.Hyperlink;
import sysmlinjava.javaannotations.requirements.RequirementSpecificationLink;
import sysmlinjava.ports.SysMLPort;
import sysmlinjava.states.StateBehaviorContext;

/**
 * Port/protocol for receiving GPS time messages
 * 
 * @author ModelerOne
 *
 */
public class GPSMessagingReceiveProtocol extends SysMLPort
{
	/**
	 * Standard that specifies the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor
	 * 
	 * @param context      block in whose context the port resides
	 * @param eventContext block to receive signal events generated by the port
	 * @param id                unique ID
	 */
	public GPSMessagingReceiveProtocol(StateBehaviorContext context, StateBehaviorContext eventContext, Long id)
	{
		super(context, Optional.of(eventContext), id);
	}

	/**
	 * Constructor
	 * 
	 * @param context block in whose context the port resides
	 * @param id           unique ID
	 */
	public GPSMessagingReceiveProtocol(StateBehaviorContext context, Long id)
	{
		super(context, id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if (signal instanceof GPSMessageSignal)
			result = new SysMLSignalEvent(signal, "GPSMessageEvent", 0L);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createSupportingInformationLinks()
	{
		protocolStandard = new SysMLHyperlink("IRS for GPS Message Receive", "file://IRS for Protocol");
	}
}