package hflink.common.ports;

import java.util.Optional;

import hflink.common.items.HTTPRequest;
import hflink.common.items.HTTPRequestString;
import hflink.common.items.HTTPResponse;
import hflink.common.signals.HTTPResponseSignal;
import sysmlinjava.annotations.SysMLHyperlink;
import sysmlinjava.common.SysMLAnything;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.javaannotations.annotations.Hyperlink;
import sysmlinjava.javaannotations.requirements.RequirementSpecificationLink;
import sysmlinjava.ports.SysMLPort;
import sysmlinjava.states.StateBehaviorContext;

/**
 * Port to simulate the client (web browser) side of the HTTP protocol
 * 
 * @author ModelerOne
 *
 */
public class HTTPClient extends SysMLPort
{
	/**
	 * Standard that specifies the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor
	 * 
	 * @param context      block (web browser) in whose context the port resides
	 * @param eventContext block (web browser) whose state machine is to receive
	 *                     events generated by this protocol
	 * @param id           unique ID
	 */
	public HTTPClient(StateBehaviorContext context, StateBehaviorContext eventContext, Long id)
	{
		super(context, Optional.of(eventContext), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLAnything object)
	{
		SysMLSignalEvent result = null;
		if (object instanceof HTTPResponse)
			result = new SysMLSignalEvent(new HTTPResponseSignal((HTTPResponse)object), "HTTPResponseEvent", 0L);
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLAnything serverObjectFor(SysMLAnything clientObject)
	{
		SysMLAnything result = null;
		if (clientObject instanceof HTTPRequestString)
		{
			HTTPRequestString httpRequestString = (HTTPRequestString)clientObject;
			HTTPRequest httpRequest = new HTTPRequest(httpRequestString);
			httpRequest.ipSource = httpRequestString.ipSource;
			httpRequest.ipDestination = httpRequestString.ipDestination;
			httpRequest.udpPort = 0;
			result = httpRequest;
		}
		else
			logger.warning("unexpected client object type: " + clientObject.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createSupportingInformationLinks()
	{
		protocolStandard = new SysMLHyperlink("Hypertext Transfer Protocol Version 3 (HTTP/3)", "https://quicwg.org/base-drafts/draft-ietf-quic-http.html");
	}
}
