package hflink.common.ports;

import java.util.Optional;

import hflink.common.items.HTTPRequest;
import hflink.common.items.HTTPResponse;
import hflink.common.items.HTTPResponseString;
import hflink.common.signals.HTTPRequestSignal;
import sysmlinjava.annotations.SysMLHyperlink;
import sysmlinjava.common.SysMLAnything;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.javaannotations.annotations.Hyperlink;
import sysmlinjava.javaannotations.requirements.RequirementSpecificationLink;
import sysmlinjava.ports.SysMLPort;
import sysmlinjava.states.StateBehaviorContext;

/**
 * Port to simulate the server (web server) side of the HTTP protocol
 * 
 * @author ModelerOne
 *
 */
public class HTTPServer extends SysMLPort
{
	/**
	 * Standard that specifies the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor
	 * 
	 * @param context      block (web server) in whose context the port resides
	 * @param eventContext block (web server) to receive signal events
	 *                          generated by the port
	 * @param id                unique ID
	 */
	public HTTPServer(StateBehaviorContext context, StateBehaviorContext eventContext, Long id)
	{
		super(context, Optional.of(eventContext), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLAnything object)
	{
		SysMLSignalEvent result = null;
		if (object instanceof HTTPRequest)
			result = new SysMLSignalEvent(new HTTPRequestSignal((HTTPRequest)object), "HTTPResponseEvent", 0L);
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLAnything serverObjectFor(SysMLAnything clientObject)
	{
		SysMLAnything result = null;
		if (clientObject instanceof HTTPResponseString)
		{
			HTTPResponseString httpResponseString = (HTTPResponseString)clientObject;
			HTTPResponse httpResponse = new HTTPResponse(httpResponseString);
			httpResponse.ipSource = httpResponseString.ipSource;
			httpResponse.ipDestination = httpResponseString.ipDestination;
			httpResponse.udpPort = 0;
			result = httpResponse;
		}
		else
			logger.warning("unexpected client object type: " + clientObject.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createSupportingInformationLinks()
	{
		protocolStandard = new SysMLHyperlink("Hypertext Transfer Protocol Version 3 (HTTP/3)", "https://quicwg.org/base-drafts/draft-ietf-quic-http.html");
	}
}
