package hflink.common.ports;

import java.util.Optional;
import hflink.common.events.HTTPResponseEvent;
import hflink.common.objects.HTTPRequest;
import hflink.common.objects.HTTPRequestString;
import sysmlinjava.annotations.comments.Hyperlink;
import sysmlinjava.annotations.requirements.RequirementSpecificationLink;
import sysmlinjava.blocks.SysMLBlock;
import sysmlinjava.comments.SysMLHyperlink;
import sysmlinjava.common.SysMLClass;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.ports.SysMLFullPort;
import hflink.common.objects.HTTPResponse;

/**
 * Port to simulate the client (web browser) side of the HTTP protocol
 * 
 * @author ModelerOne
 *
 */
public class HTTPClient extends SysMLFullPort
{
	/**
	 * Standard that specifies the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor
	 * 
	 * @param contextBlock      block (web browser) in whose context the port
	 *                          resides
	 * @param eventContextBlock block (web browser) whose state machine is to
	 *                          receive events generated by this protocol
	 * @param id                unique ID
	 */
	public HTTPClient(SysMLBlock contextBlock, SysMLBlock eventContextBlock, Long id)
	{
		super(contextBlock, Optional.of(eventContextBlock), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLClass object)
	{
		SysMLSignalEvent result = null;
		if (object instanceof HTTPResponse)
			result = new HTTPResponseEvent((HTTPResponse)object);
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLClass serverObjectFor(SysMLClass clientObject)
	{
		SysMLClass result = null;
		if (clientObject instanceof HTTPRequestString)
		{
			HTTPRequestString httpRequestString = (HTTPRequestString)clientObject;
			HTTPRequest httpRequest = new HTTPRequest(httpRequestString);
			httpRequest.ipSource = httpRequestString.ipSource;
			httpRequest.ipDestination = httpRequestString.ipDestination;
			httpRequest.udpPort = 0;
			result = httpRequest;
		}
		else
			logger.warning("unexpected client object type: " + clientObject.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createHyperlinks()
	{
		protocolStandard = new SysMLHyperlink("Hypertext Transfer Protocol Version 3 (HTTP/3)", "https://quicwg.org/base-drafts/draft-ietf-quic-http.html");
	}
}
