package hflink.common.ports;

import java.util.Optional;

import hflink.common.items.IPPacket;
import hflink.common.items.UDPDatagram;
import hflink.common.signals.IPPacketSignal;
import sysmlinjava.annotations.SysMLHyperlink;
import sysmlinjava.common.SysMLAnything;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.javaannotations.annotations.Hyperlink;
import sysmlinjava.javaannotations.requirements.RequirementSpecificationLink;
import sysmlinjava.ports.SysMLPort;
import sysmlinjava.states.StateBehaviorContext;

/**
 * Port to simulate the internet protocol (IP)
 * 
 * @author ModelerOne
 *
 */
public class IP extends SysMLPort
{
	/**
	 * Standard that specifies the protocol
	 */
	@RequirementSpecificationLink
	@Hyperlink
	public SysMLHyperlink protocolStandard;

	/**
	 * Constructor
	 * 
	 * @param context      block in whose context the port resides
	 * @param eventContext block to receive signal events generated by the port
	 * @param id                unique ID
	 */
	public IP(StateBehaviorContext context, StateBehaviorContext eventContext, Long id)
	{
		super(context, Optional.of(eventContext), id);
	}

	/**
	 * Constructor
	 * 
	 * @param context block in whose context the port resides
	 * @param id           unique ID
	 */
	public IP(StateBehaviorContext context, Long id)
	{
		super(context, id);
	}

	@Override
	protected SysMLAnything serverObjectFor(SysMLAnything clientObject)
	{
		SysMLAnything result = null;
		if (clientObject instanceof UDPDatagram)
			result = new IPPacket(
				((UDPDatagram)clientObject).sourceIPAddress,
				((UDPDatagram)clientObject).destinationIPAddress,
				(UDPDatagram)clientObject);
		else
			logger.warning("unexpected client object type: " + clientObject.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLAnything clientObjectFor(SysMLAnything serverObject)
	{
		SysMLAnything result = null;
		if (serverObject instanceof IPPacket)
			result = ((IPPacket)serverObject).data;
		else
			logger.warning("unexpected serverObject type: " + serverObject.getClass().getSimpleName());
		return result;
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLAnything object)
	{
		SysMLSignalEvent result = null;
		if (object instanceof IPPacket)
			result = new SysMLSignalEvent(new IPPacketSignal(new IPPacket((IPPacket)object)), "IPPacketEvent", 0L);
		else
			logger.warning("unexpected object type: " + object.getClass().getSimpleName());
		return result;
	}

	@Override
	protected void createSupportingInformationLinks()
	{
		protocolStandard = new SysMLHyperlink("IETF RFC-791 Internet Protocol", "https://tools.ietf.org/html/rfc791");
	}
}
