package motorinwheel.common.events;

import motorinwheel.common.signals.HydraulicPressureSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.valuetypes.ForceNewtonsPerMeterSquare;

/**
 * Event for the occurence of a value of pressure force generated by a hydraulic
 * line
 * 
 * @author ModelerOne
 *
 */
public class HydraulicPressureEvent extends SysMLSignalEvent
{
	public HydraulicPressureEvent(ForceNewtonsPerMeterSquare force)
	{
		super("HydraulicPressure");
		((HydraulicPressureSignal)signal).force.value = force.value;
	}

	public ForceNewtonsPerMeterSquare getForce()
	{
		return ((HydraulicPressureSignal)signal).force;
	}

	@Override
	public void createSignal()
	{
		signal = new HydraulicPressureSignal(new ForceNewtonsPerMeterSquare(), 0L);
	}
}
