package motorinwheel.common.events;

import motorinwheel.common.signals.MotorTorqueSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.valuetypes.TorqueNewtonMeters;

/**
 * Event for the occurence of a value of torque generated by a motor
 * 
 * @author ModelerOne
 *
 */
public class MotorTorqueEvent extends SysMLSignalEvent
{
	public MotorTorqueEvent(TorqueNewtonMeters torque)
	{
		super("MotorTorque");
		((MotorTorqueSignal)signal).torque.value = torque.value;
	}

	public TorqueNewtonMeters getTorque()
	{
		return ((MotorTorqueSignal)signal).torque;
	}

	@Override
	public void createSignal()
	{
		signal = new MotorTorqueSignal(new TorqueNewtonMeters());
	}
}
