package connectedtanks;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;

import sysmlinjava.attributetypes.DurationSeconds;
import sysmlinjava.attributetypes.Point2D;
import sysmlinjava.connectors.SysMLBindingConnector;
import sysmlinjava.connectors.SysMLFlowConnector;
import sysmlinjava.javaannotations.analysis.parametrics.ParametricAnalysis;
import sysmlinjava.javaannotations.connectors.BindingConnector;
import sysmlinjava.javaannotations.connectors.FlowConnector;
import sysmlinjava.javaannotations.parts.Part;
import sysmlinjava.parts.SysMLPart;
import sysmlinjava.views.common.Axis;
import sysmlinjava.views.common.AxisFixedRange;
import sysmlinjava.views.linechart.LineChartData;
import sysmlinjava.views.linechart.LineChartDefinition;
import sysmlinjava.views.linechart.LineChartsDisplay;
import sysmlinjava.views.linechart.LineChartsTransmitter;

/**
 * {@code ConnectedTanks} is a SysMLinJava model of a simple system of two tanks
 * of fluid connected by a pipe. The model is a SysMLinJava implementation of
 * the model by the same name described in "SysML Extension for Physical
 * Interaction and Signal Flow Simulation", Object Management Group, Inc., 2018.
 * The concept of the connected tanks system is the use of the SysML proxy port
 * to model the interface between tank and pipe, and the use of the SysML
 * constraint block to perform parametric specification and analysis of the
 * system model.
 * <p>
 * {@code ConnectedTanks} consists of three parts, the two tanks,
 * {@code fluidReservoir1} and {@code fluidReservoir2}, and the {@code pipe}
 * that connects them. The two tanks have different levels of fluid which
 * equalize via the fluid flow through the pipe. It also consists of three
 * constraint blocks, one for each tank and the pipe. The properties of the
 * tanks and pipe (fluid flows, pressures, etc.) are obtained from the
 * constraints in the constraint blocks associated with each. These constraints
 * are specified in the {@code tank1Analysis}, {@code tank2Analysis}, and
 * {@code pipeAnalysis}. In essence, the SysMLinJava model of the connected
 * tanks is an executable model of a system defined by its constraints where the
 * model is verified/validated by its conformance to the system's constraints.
 * <p>
 * The tanks and pipe each have a proxy port that represents its interface with
 * the pipe or tanks, respectively. These proxy ports include values for the
 * fluid flows and pressures at the interface at any instant in the model
 * execution. As the fluid flows between the tanks via the pipe, the pressures
 * at the interface change, thereby changing the fluid flow, which results in a
 * slower rate of change for (time-based derivative of) the tank fluid levels.
 * It is these tank fluid levels over time that are displayed on a line chart
 * generated by the {@code ConnectedTanks} block during model execution.
 * 
 * @see <a href="http://www.omg.org/spec/SysPhS/1.0/PDF">SysML Extension for
 *      Physical Interaction and Signal Flow Simulation</a>
 * @author ModelerOne
 */
public class ConnectedTanks extends SysMLPart
{
	/**
	 * Tank which acts as a first fluid reservoir
	 */
	@Part
	Tank fluidReservoir1;
	/**
	 * Tank which acts as a second fluid reservoir
	 */
	@Part
	Tank fluidReservoir2;
	/**
	 * Pipe that connects the two tanks allowing fluid to move (equalize) between
	 * them
	 */
	@Part
	Pipe pipe;

	/**
	 * Constraint block that constrains the first tank to specified parameters
	 */
	@ParametricAnalysis
	TankAnalysis tank1Analysis;
	/**
	 * Constraint block that constrains the second tank to specified parameters
	 */
	@ParametricAnalysis
	TankAnalysis tank2Analysis;
	/**
	 * Constraint block that constrains the pipe to specified parameters
	 */
	@ParametricAnalysis
	PipeAnalysis pipeAnalysis;

	/**
	 * Connector between the tank 1 and pipe opening 1
	 */
	@FlowConnector
	public SysMLFlowConnector tank1ToPipe1Connector;
	/**
	 * Connector between the tank 2 and pipe opening 2
	 */
	@FlowConnector
	public SysMLFlowConnector tank2ToPipe2Connector;
	////////////////////////////////////////////////////////
	/**
	 * Connector that binds the tank's pressure to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank1PressureConnector;
	/**
	 * Connector that binds the tank's fluid flow to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank1FluidFlowConnector;
	/**
	 * Connector that binds the tank's fluid level to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank1FluidLevelConnector;
	/**
	 * Connector that binds the tank's fluid density to parametric analysis
	 * parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank1FluidDensityConnector;
	/**
	 * Connector that binds the tank's surface area to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank1SurfaceAreaConnector;
	////////////////////////////////////////////////////////
	/**
	 * Connector that binds the tank's pressure to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank2PressureConnector;
	/**
	 * Connector that binds the tank's fluid flow to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank2FluidFlowConnector;
	/**
	 * Connector that binds the tank's fluid level to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank2FluidLevelConnector;
	/**
	 * Connector that binds the tank's fluid density to parametric analysis
	 * parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank2FluidDensityConnector;
	/**
	 * Connector that binds the tank's surface area to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector tank2SurfaceAreaConnector;

	///////////////////////////////////////////////////////////////////////////////////////
	/**
	 * Connector that binds the pipes pressure at opening to tank 1 to constraint
	 * parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipeOpening1PressureConnector;
	/**
	 * Connector that binds the pipes pressure at opening to tank 2 to constraint
	 * parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipsOpening2PressureConnector;
	/**
	 * Connector that binds the pipes fluid flow at opening to tank 1 to constraint
	 * parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipeOpening1FluidFlowConnector;
	/**
	 * Connector that binds the pipes fluid flow at opening to tank 2 to constraint
	 * parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipeOpening2FluidFlowConnector;
	/**
	 * Connector that binds the pipes radius to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipeRadiusConnector;
	/**
	 * Connector that binds the pipes length to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipeLengthConnector;
	/**
	 * Connector that binds the pipes fluid flow to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipeFluidFlowConnector;
	/**
	 * Connector that binds the pipes pressure differential to parametric analysis
	 * parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipePressureDiffConnector;
	/**
	 * Connector that binds the pipes viscosity to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipeViscosityConnector;
	/**
	 * Connector that binds the pipes resistance to parametric analysis parameter
	 */
	@BindingConnector
	SysMLBindingConnector pipeResistanceConnector;

	/**
	 * Transmitter of parametric analysis parameter values to a line chart display
	 */
	public LineChartsTransmitter lineChartsTransmitter;

	/**
	 * Title of the line chart
	 */
	static final String lineChartTitle = "Connected Tanks Fluid Heigths";

	/**
	 * Constructor
	 */
	public ConnectedTanks()
	{
		super();
		lineChartsTransmitter = new LineChartsTransmitter(LineChartsDisplay.udpPort, true);
		transmitLineChartDefinition();
	}

	@Override
	public void start()
	{
		/*
		 * Start the analysis cases
		 */
		logger.info("starting");
		/*
		 * Initialize analysis cases' constant parameters by invoking attribute-observing binding
		 * connectors just this one time
		 */
		pipe.pipeLength.setValue(pipe.pipeLength);
		pipe.pipeRadius.setValue(pipe.pipeRadius);
		pipe.dynamicViscosity.setValue(pipe.dynamicViscosity);
		pipe.resistance.setValue(pipe.resistance);
		
		fluidReservoir1.area.setValue(fluidReservoir1.area);
		fluidReservoir2.area.setValue(fluidReservoir2.area);
		fluidReservoir1.fluidDensity.setValue(fluidReservoir1.fluidDensity);
		fluidReservoir2.fluidDensity.setValue(fluidReservoir2.fluidDensity);
	}

	@Override
	public void stop()
	{
		logger.info("stopping");
	}

	/**
	 * Increments the model execution to the next increment of time
	 * 
	 * @param i index of the next increment of time
	 */
	public void increment(int i)
	{
		pipe.increment();
		transmitLineChartData(DurationSeconds.of(i));
	}

	@Override
	protected void createParts()
	{
		fluidReservoir1 = new Tank("Tank1", 1L);
		fluidReservoir2 = new Tank("Tank2", 2L);
		pipe = new Pipe("Pipe", 0L);
	}

	@Override
	protected void createAnalysisCases()
	{
		tank1Analysis = new TankAnalysis("tank1Analysis");
		tank2Analysis = new TankAnalysis("tank2Analysis");
		pipeAnalysis = new PipeAnalysis("pipeAnalysis");
	}

	@Override
	protected void createFlowConnectors()
	{
		tank1ToPipe1Connector = new SysMLFlowConnector(pipe.pipeOpening1, fluidReservoir1.tankOpening, "Pipe1ToTank1", 0L);
		tank2ToPipe2Connector = new SysMLFlowConnector(pipe.pipeOpening2, fluidReservoir2.tankOpening, "Pipe2ToTank2", 0L);
	}

	@Override
	protected void createBindingConnectors()
	{
		tank1FluidDensityConnector = new SysMLBindingConnector(fluidReservoir1.fluidDensity, tank1Analysis, TankParams.fluidDensity.toString());
		tank1FluidFlowConnector = new SysMLBindingConnector(fluidReservoir1.fluidFlow, tank1Analysis, TankParams.fluidFlow.toString());
		tank1FluidLevelConnector = new SysMLBindingConnector(fluidReservoir1.fluidLevel, tank1Analysis, TankParams.fluidHeight.toString());
		tank1PressureConnector = new SysMLBindingConnector(fluidReservoir1.pressure, tank1Analysis, TankParams.pressure.toString());
		tank1SurfaceAreaConnector = new SysMLBindingConnector(fluidReservoir1.area, tank1Analysis, TankParams.surfaceArea.toString());

		tank2FluidDensityConnector = new SysMLBindingConnector(fluidReservoir2.fluidDensity, tank2Analysis, TankParams.fluidDensity.toString());
		tank2FluidFlowConnector = new SysMLBindingConnector(fluidReservoir2.fluidFlow, tank2Analysis, TankParams.fluidFlow.toString());
		tank2FluidLevelConnector = new SysMLBindingConnector(fluidReservoir2.fluidLevel, tank2Analysis, TankParams.fluidHeight.toString());
		tank2PressureConnector = new SysMLBindingConnector(fluidReservoir2.pressure, tank2Analysis, TankParams.pressure.toString());
		tank2SurfaceAreaConnector = new SysMLBindingConnector(fluidReservoir2.area, tank2Analysis, TankParams.surfaceArea.toString());

		pipeFluidFlowConnector = new SysMLBindingConnector(pipe.fluidFlow, pipeAnalysis, PipeParams.fluidFlow.toString());
		pipeLengthConnector = new SysMLBindingConnector(pipe.pipeLength, pipeAnalysis, PipeParams.length.toString());
		pipeOpening1FluidFlowConnector = new SysMLBindingConnector(pipe.pipeOpening1.vf.q, pipeAnalysis, PipeParams.opening1FluidFlow.toString());
		pipeOpening1PressureConnector = new SysMLBindingConnector(pipe.pipeOpening1.vf.p, pipeAnalysis, PipeParams.opening1Pressure.toString());
		pipeOpening2FluidFlowConnector = new SysMLBindingConnector(pipe.pipeOpening2.vf.q, pipeAnalysis, PipeParams.opening2FluidFlow.toString());
		pipsOpening2PressureConnector = new SysMLBindingConnector(pipe.pipeOpening2.vf.p, pipeAnalysis, PipeParams.opening2Pressure.toString());
		pipePressureDiffConnector = new SysMLBindingConnector(pipe.fluidPressureDiff, pipeAnalysis, PipeParams.pressureDiff.toString());
		pipeRadiusConnector = new SysMLBindingConnector(pipe.pipeRadius, pipeAnalysis, PipeParams.radius.toString());
		pipeResistanceConnector = new SysMLBindingConnector(pipe.resistance, pipeAnalysis, PipeParams.resistance.toString());
		pipeViscosityConnector = new SysMLBindingConnector(pipe.dynamicViscosity, pipeAnalysis, PipeParams.viscosity.toString());

		/*
		 * Add each connector to the parametric analyses maps of binding parameter
		 * connectors for use by {@code onParameterChange()} operation to retrieve the
		 * updated param values.
		 */
		tank1Analysis.paramConnectors.put(TankParams.fluidDensity.toString(), tank1FluidDensityConnector);
		tank1Analysis.paramConnectors.put(TankParams.fluidFlow.toString(), tank1FluidFlowConnector);
		tank1Analysis.paramConnectors.put(TankParams.fluidHeight.toString(), tank1FluidLevelConnector);
		tank1Analysis.paramConnectors.put(TankParams.pressure.toString(), tank1PressureConnector);
		tank1Analysis.paramConnectors.put(TankParams.surfaceArea.toString(), tank1SurfaceAreaConnector);

		tank2Analysis.paramConnectors.put(TankParams.fluidDensity.toString(), tank2FluidDensityConnector);
		tank2Analysis.paramConnectors.put(TankParams.fluidFlow.toString(), tank2FluidFlowConnector);
		tank2Analysis.paramConnectors.put(TankParams.fluidHeight.toString(), tank2FluidLevelConnector);
		tank2Analysis.paramConnectors.put(TankParams.pressure.toString(), tank2PressureConnector);
		tank2Analysis.paramConnectors.put(TankParams.surfaceArea.toString(), tank2SurfaceAreaConnector);

		pipeAnalysis.paramConnectors.put(PipeParams.fluidFlow.toString(), pipeFluidFlowConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.pressureDiff.toString(), pipePressureDiffConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.opening1Pressure.toString(), pipeOpening1PressureConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.opening2Pressure.toString(), pipsOpening2PressureConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.opening1FluidFlow.toString(), pipeOpening1FluidFlowConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.opening2FluidFlow.toString(), pipeOpening2FluidFlowConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.radius.toString(), pipeRadiusConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.length.toString(), pipeLengthConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.viscosity.toString(), pipeViscosityConnector);
		pipeAnalysis.paramConnectors.put(PipeParams.resistance.toString(), pipeResistanceConnector);
	}

	/**
	 * Transmits the definition of the line chart of the parametric analysis
	 * parameters (tank levels) to the graphical line chart display
	 * 
	 * @see sysmlinjava.views.common.Axis
	 * @see sysmlinjava.views.linechart.LineChartDefinition
	 */
	protected void transmitLineChartDefinition()
	{
		Axis xAxis = new Axis("Duration", "seconds", Optional.of(0.0), Optional.of(100.0), 10.0, 5);
		AxisFixedRange yAxisTank1FluidLevel = new AxisFixedRange("Tank1 Fluid Level", "meters", 0.0, 45.0, 5.0, 5);
		AxisFixedRange yAxisTank2FluidLevel = new AxisFixedRange("Tank2 Fluid Level", "meters", 0.0, 45.0, 5.0, 5);
		ArrayList<AxisFixedRange> yAxes = new ArrayList<>(Arrays.asList(yAxisTank1FluidLevel, yAxisTank2FluidLevel));
		LineChartDefinition graph = new LineChartDefinition(lineChartTitle, yAxes, xAxis);
		lineChartsTransmitter.transmitGraph(graph);
	}

	/**
	 * Transmits the values of the parametric analysis parameters (tank levels) to
	 * the graphical line chart display
	 * 
	 * @param duration time since start of connected tanks simulation
	 * @see sysmlinjava.attributetypes.Point2D
	 * @see sysmlinjava.views.linechart.LineChartData
	 */
	protected void transmitLineChartData(DurationSeconds duration)
	{
		List<Point2D> xyTank1FluidLevel = new ArrayList<>(Arrays.asList(new Point2D(duration.value, fluidReservoir1.fluidLevel.value)));
		List<Point2D> xyTank2FluidLevel = new ArrayList<>(Arrays.asList(new Point2D(duration.value, fluidReservoir2.fluidLevel.value)));
		List<List<Point2D>> xyListList = new ArrayList<>(Arrays.asList(xyTank1FluidLevel, xyTank2FluidLevel));
		LineChartData graphData = new LineChartData(lineChartTitle, xyListList);
		lineChartsTransmitter.transmitGraphData(graphData);
	}

	/**
	 * Main operation that executes the model. Execution starts with construction of
	 * the connected tanks domain, followed by the repeated incremental update of
	 * the tanks' and pipe's properties until the tank levels are essentially
	 * equalized.
	 * 
	 * @param args arguments (not used)
	 */
	public static void main(String[] args)
	{
		ConnectedTanks domain = new ConnectedTanks();
		domain.start();
		domain.delay(1.0);
		int i = 0;
		while (domain.fluidReservoir1.fluidLevel.subtracted(domain.fluidReservoir2.fluidLevel).absoluted().greaterThan(0.05))
		{
			domain.increment(i++);
			domain.delay(1.0);
		}
		domain.stop();
		System.exit(0);
	}
}
