package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.events.AcceleratorPedalForceEvent;
import motorinwheel.common.signals.AcceleratorPedalForceSignal;
import sysmlinjava.blocks.SysMLBlock;
import sysmlinjava.common.SysMLSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.ports.SysMLFullPort;

/**
 * Port to receive the force on an accelerator pedal
 * 
 * @author ModelerOne
 *
 */
public class AcceleratorPedalForceReceivePort extends SysMLFullPort
{
	/**
	 * Constructor
	 * 
	 * @param contextBlock      block in whose context the port resides
	 * @param eventContextBlock block to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public AcceleratorPedalForceReceivePort(SysMLBlock contextBlock, SysMLBlock eventContextBlock, Long id)
	{
		super(contextBlock, Optional.of(eventContextBlock), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if (signal instanceof AcceleratorPedalForceSignal)
			result = new AcceleratorPedalForceEvent(((AcceleratorPedalForceSignal)signal).force, id);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}
}
