package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.events.BrakePedalForceEvent;
import motorinwheel.common.signals.BrakePedalForceSignal;
import sysmlinjava.blocks.SysMLBlock;
import sysmlinjava.common.SysMLSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.ports.SysMLFullPort;

/**
 * Port to receive the operator's force on the brake pedal
 * 
 * @author ModelerOne
 *
 */
public class BrakePedalForceReceivePort extends SysMLFullPort
{
	
	/**
	 * Constructor
	 * 
	 * @param contextBlock      block in whose context the port resides
	 * @param eventContextBlock block to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public BrakePedalForceReceivePort(SysMLBlock contextBlock, SysMLBlock eventContextBlock, Long id)
	{
		super(contextBlock, Optional.of(eventContextBlock), id);
	}

	protected BrakePedalForceReceivePort(SysMLBlock contextBlock, Long id)
	{
		super(contextBlock, id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if(signal instanceof BrakePedalForceSignal)
			result = new BrakePedalForceEvent(((BrakePedalForceSignal)signal).force, id);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}
}
