package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.signals.BrakePedalForceSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.items.SysMLSignal;
import sysmlinjava.parts.SysMLPart;
import sysmlinjava.ports.SysMLPort;

/**
 * Port to receive the operator's force on the brake pedal
 * 
 * @author ModelerOne
 *
 */
public class BrakePedalForceReceivePort extends SysMLPort
{
	
	/**
	 * Constructor
	 * 
	 * @param contextPart      part in whose context the port resides
	 * @param eventContextPart part to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public BrakePedalForceReceivePort(SysMLPart contextPart, SysMLPart eventContextPart, Long id)
	{
		super(contextPart, Optional.of(eventContextPart), id);
	}

	protected BrakePedalForceReceivePort(SysMLPart contextPart, Long id)
	{
		super(contextPart, id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if(signal instanceof BrakePedalForceSignal)
			result = new SysMLSignalEvent(signal, "BrakePedalForce", 0L);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}
}
