package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.events.ElectricPowerEvent;
import motorinwheel.common.signals.ElectricalPowerSignal;
import motorinwheel.components.motor.ElectricMotor;
import sysmlinjava.blocks.SysMLBlock;
import sysmlinjava.common.SysMLSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.ports.SysMLFullPort;

/**
 * Port to receive electrical power
 * 
 * @author ModelerOne
 *
 */
public class ElectricalPowerReceivePort extends SysMLFullPort
{
	/**
	 * Constructor
	 * 
	 * @param contextBlock      block in whose context the port resides
	 * @param eventContextBlock block to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public ElectricalPowerReceivePort(SysMLBlock contextBlock, ElectricMotor eventContextBlock, Long id)
	{
		super(contextBlock, Optional.of(eventContextBlock), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if(signal instanceof ElectricalPowerSignal)
			result = new ElectricPowerEvent(((ElectricalPowerSignal)signal).power);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}
}
