package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.signals.HydraulicPressureSignal;
import motorinwheel.components.brake.MechanicalBrake;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.items.SysMLSignal;
import sysmlinjava.parts.SysMLPart;
import sysmlinjava.ports.SysMLPort;

/**
 * Port to receive the pressure force of a hydraulic line
 * 
 * @author ModelerOne
 *
 */
public class HydraulicForceReceivePort extends SysMLPort
{
	/**
	 * Constructor
	 * 
	 * @param contextPart      part in whose context the port resides
	 * @param eventContextPart part to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public HydraulicForceReceivePort(SysMLPart contextPart, MechanicalBrake eventContextPart, Long id)
	{
		super(contextPart, Optional.of(eventContextPart), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if (signal instanceof HydraulicPressureSignal)
			result = new SysMLSignalEvent(signal, "HydraulicPressure", 0L);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}
}
