package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.events.HydraulicPressureEvent;
import motorinwheel.common.signals.HydraulicPressureSignal;
import motorinwheel.components.brake.MechanicalBrake;
import sysmlinjava.blocks.SysMLBlock;
import sysmlinjava.common.SysMLSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.ports.SysMLFullPort;

/**
 * Port to receive the pressure force of a hydraulic line
 * 
 * @author ModelerOne
 *
 */
public class HydraulicForceReceivePort extends SysMLFullPort
{
	/**
	 * Constructor
	 * 
	 * @param contextBlock      block in whose context the port resides
	 * @param eventContextBlock block to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public HydraulicForceReceivePort(SysMLBlock contextBlock, MechanicalBrake eventContextBlock, Long id)
	{
		super(contextBlock, Optional.of(eventContextBlock), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if (signal instanceof HydraulicPressureSignal)
			result = new HydraulicPressureEvent(((HydraulicPressureSignal)signal).force);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}
}
