package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.signals.MechanicalForceSignal;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.items.SysMLSignal;
import sysmlinjava.parts.SysMLPart;
import sysmlinjava.ports.SysMLPort;

/**
 * Port to receive mechanical force
 * 
 * @author ModelerOne
 *
 */
public class MechanicalForceReceivePort extends SysMLPort
{
	/**
	 * Constructor
	 * 
	 * @param contextPart      part in whose context the port resides
	 * @param eventContextPart part to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public MechanicalForceReceivePort(SysMLPart contextPart, SysMLPart eventContextPart, Long id)
	{
		super(contextPart, Optional.of(eventContextPart), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if(signal instanceof MechanicalForceSignal)
			result = new SysMLSignalEvent(signal, "MechanicalForce", 0L);
		else
			logger.warning("unexpected signal type: " + signal.getClass().getSimpleName());
		return result;
	}
}
