package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.signals.MechanicalForceSignal;
import motorinwheel.components.suspensionchassisbody.SuspensionChassisBody;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.items.SysMLSignal;
import sysmlinjava.parts.SysMLPart;
import sysmlinjava.ports.SysMLPort;

/**
 * Port to receive the weight force of a motor on the suspension
 * 
 * @author ModelerOne
 *
 */
public class MotorSuspensionMountForceReceivePort extends SysMLPort
{
	/**
	 * Constructor
	 * 
	 * @param contextPart      part in whose context the port resides
	 * @param eventContextPart part to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public MotorSuspensionMountForceReceivePort(SysMLPart contextPart, SuspensionChassisBody eventContextPart, Long id)
	{
		super(contextPart, Optional.of(eventContextPart), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if (signal instanceof MechanicalForceSignal)
			result = new SysMLSignalEvent(signal, "MotorSuspensionForce", 0L);
		return result;
	}
}
