







package motorinwheel.common.ports.energy;

import java.util.Optional;
import motorinwheel.common.signals.MotorTorqueSignal;
import motorinwheel.components.wheel.Wheel;
import sysmlinjava.events.SysMLSignalEvent;
import sysmlinjava.items.SysMLSignal;
import sysmlinjava.parts.SysMLPart;
import sysmlinjava.ports.SysMLPort;

/**
 * Port to receive the torque on the wheel from the motor
 * 
 * @author ModelerOne
 *
 */
public class MotorTorqueReceivePort extends SysMLPort
{
	/**
	 * Constructor
	 * 
	 * @param contextPart      part in whose context the port resides
	 * @param eventContextPart part to receive the receive events generated by
	 *                          this port
	 * @param id                unique ID
	 */
	public MotorTorqueReceivePort(SysMLPart contextPart, Wheel eventContextPart, Long id)
	{
		super(contextPart, Optional.of(eventContextPart), id);
	}

	@Override
	protected SysMLSignalEvent eventFor(SysMLSignal signal)
	{
		SysMLSignalEvent result = null;
		if (signal instanceof MotorTorqueSignal)
			result = new SysMLSignalEvent(signal, "MotorTorque", 0L);
		return result;
	}
}
